# Generated by Django 5.0.4 on 2024-04-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_logininfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logininfo',
        ),
    ]
