# Generated by Django 5.0.4 on 2024-04-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_logininfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='logininfo',
            fields=[
                ('userid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
